spring.application.name=operon

spring.datasource.url=jdbc:postgresql://localhost:5432/operon
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=local

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000